### ISSUE TITLE
Set up server

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/project-monitoring-app#1]
- [x] Move d2-docker to /data
- [x] Install d2-docker v2.32.2 -> dev2.est.com:8081 with Sierra Leone DB

**Comment by tokland** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5daea9b2d9d3a5000fd5a841/attachments/5db02ffdd9d3a5000fd5e5c6)

admin / same-than-always
