### ISSUE TITLE
ObjectsTable styles

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/project-monitoring-app#131]
- [ ] The contextual menu top-right corner should match the 3-dots
- [ ] The original table used to be a bit more greyish for the font (check maintenance)
- [ ] Check if possible to keep the row selected on right-button contextual open.

---
https://github.com/EyeSeeTea/project-monitoring-app/pull/126#issuecomment-577283379

**Comment by adrianq** [comment]
Moved to clickup as a general task to review styles of the components
