### ISSUE TITLE
Test refinement

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/project-monitoring-app#157]
- [x] Add d2-docker infrastructure / travis (check metadata-sync, development-malaria).
- [x] Connect to cypress video. Readd cypress key
- [x] Check why electron browser not working (maybe problem with app-runtime? but how comes it does work in metadata-sync?)
- [x] Check error with POST zip. When working, remove local server and use apps/api/...
- [x] Use installed app for tests (solve first the weird error of curl POST) so we can use pages with iframes (data entry)
- [ ] Add more cypress tests: 
  - [x] Actual/target values
  - [ ] MER -> all open to another issue(s)
  - [ ] Download
  - [ ] Test by role

**Comment by adrianq** [comment]
This is a lifetime work that will always be around us like an angel or a demon. It will be on our everyday prayers and we don't need a task for this anymore
