### ISSUE TITLE
Actual values on non-open periods fail

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/project-monitoring-app#167]
- [ ] Check why accessing a month in the future breaks the rendering (even when returning on a valid month)
- [ ] Hide non-open periods

**Comment by adrianq** [comment]
See blessed issues:
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/5
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/23
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/39
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/62
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/63
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/76
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/77
