### ISSUE TITLE
Refine permissions including authorities for messaging, interpretations and other DHIS2 features

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/project-monitoring-app#171]
- [x] Authorities: "M_dhis-web-messaging", "M_dhis-web-interpretation"
- [x] Review what we need to do for users to see other users -> a user cannot see other users when they have common user roles (bug? check with debugger)

**Comment by tokland** [comment]
Authorities:

"M_dhis-web-messaging"
"M_dhis-web-interpretation"

metadata updated and deployed to 8087

**Comment by adrianq** [comment]
Review what we need to do for users to see other users

**Comment by tokland** [comment]
Non-superadmin users were not seeing other users. We saw that this happened whenever some of the users shared some user roles. We couldn't reproduce this behavior in play2 instances.  A debug session has been necessary. First, we found the code location where the query did that userRoles intersection logic ([here](https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/hibernate/HibernateUserStore.java#L224)).  This `disjointRoles` boolean was set [here](https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/user/DefaultUserService.java#L240). So, the system seteting "Allow users to grant own user roles" was the origin of the problem (see [docs](https://docs.dhis2.org/2.32/en/user/html/system_access_settings.html)). Conclusions:

- Apparently, the logic to simply get users applies this "grant own roles" restriction. This is known limitation by the community: [here](https://community.dhis2.org/t/dhis2-incoming-sms/2978/2) and [here](https://community.dhis2.org/t/sms-not-finding-users-associated-with-phones/3468).
- Solution: Simply enable the settting: "allow users to grant own user roles". Already done in dev2:8087.
