### ISSUE TITLE
Refine OrgUnits and users

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/project-monitoring-app#193]
- [ ] An admin should see all projects in any org unit (TBD)
- [ ] Multiple roots: ![image](https://app.gitkraken.com/api/glo/boards/5daea9b2d9d3a5000fd5a841/attachments/5e53801f757b7a00112de994)
- [ ] Currently, a user must have a Capture orgUnit  to be able to see in listings and see it as root in countries. Should we accept that a user can see countries if a root orgunit (level=1) is selected?

**Comment by adrianq** [comment]
Not relevant any more
