### ISSUE TITLE
Review why dashboard, data entry and data approval  seem not to be showing the latest data

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/project-monitoring-app#245]
- [x] Last years -> comment on JIRA Issue -> adrian

See:
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/118
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/115
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/108
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/107
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/106
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/95

**Comment by tokland** [comment]
All those issue are related with analytics endpoint not returning update values.

Setting Scheduler -> Analytics -> Last year to a value fixes this. See:
https://jira.dhis2.org/browse/DHIS2-4664?focusedCommentId=34448&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-34448

https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/115 could not be reproduced, only an error on loadValues could explain it, but should not happend on normally-operationally network.
