### ISSUE TITLE
When data is downloaded and exported to excel, no values are appearing in the table

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/project-monitoring-app#249]
In theory this happens only with the user stood (created by them so they might be misconfiguration). See https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/109

**Comment by tokland** [comment]
Setting Scheduler -> Analytics -> Last year to a value fixes this. See:
https://jira.dhis2.org/browse/DHIS2-4664?focusedCommentId=34448&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-34448
