### ISSUE TITLE
Set up Amazon Backup

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/project-monitoring-app#259]
- [x] Test snapshot in Amazon console (limitations?)
- [x] Check if we can create snapshot using CLI/API.
- [x] Check if there is a UI scheduler to set up automatic snapshots.

**Comment by tokland** [comment]
## How to do a snapshow

https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Snapshots:sort=snapshotId

[Create snapshot]
Select resource type: Instance
Instance: DHIS2- Projects (Test)
Description: ..
[Create snapshot]

Also:

Volumes -> Right-click Snapshot

## Limitations

You can do as many snapshots as you want, you will be billed for Gb. Snapshots are incremental.

More info:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSSnapshots.html

## Create a snapshot using the API

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSnapshot.html

## Schedule

Go to Instancs or Elastic Block Store->Volumes and tag it: SnapshotMonthly=True

Elastic Block Store
Lifecycle Manager
[Create Snapshot lifecycle manager]
Target with these tags: SnapshotMonthly=True
Select periodicity
Retain: N (number of old snapshots history to keep)

[Create]

(Note: the create button does not work for our user - without visible error-, nor the listing of existing lifecyles: `is not authorized to perform: dlm:GetLifecyclePolicies`)

**Comment by adrianq** [comment]
We are waiting for SP regarding the approach to follow. Pending task:
- [ ] ask them label the EBS for the testing environment though.
