### ISSUE TITLE
Update countries and project location

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/project-monitoring-app#278]
https://docs.google.com/spreadsheets/d/1X-eQ02Jg8XI0eIuOKnICi99tHgoIQILu/edit#gid=1672601967

**Comment by adrianq** [comment]
Waiting for the client to send the information

**Comment by tokland** [comment]
https://bitbucket.org/eyeseetea/project-monitoring-metadata/pull-requests/21/update-countries-locations

- [ ] It will be necessary to delete old locations, I have the ids, so it's only POST /metadata as a delete to every server.
