### ISSUE TITLE
Check users-app

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/project-monitoring-app#309]
- [x] Report issue if necessary

https://app.gitkraken.com/glo/view/card/60c3e9e30b0f4f47b995786f5bdebf8c

**Comment by tokland** [comment]
It's a problem with the pagination of the users controller (which does not use the default CRUD controller, which works fine). It's been already reported:

https://jira.dhis2.org/browse/DHIS2-9454
https://jira.dhis2.org/browse/DHIS2-8863

I've added a comment on the first ticket so they know it's affecting more people and hinting where the problem may be.

**Comment by adrianq** [comment]
I have watched both issues as well. I will let SP know and for now, I think we can close this issues
