### ISSUE TITLE
Remove org unit filters

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/project-monitoring-app#38]
Modify d2-ui-comp to make filter customisable (show/hide)

![image](https://app.gitkraken.com/api/glo/boards/5daea9b2d9d3a5000fd5a841/attachments/5dd3e47b5b8585000f1f638d)

**Comment by laurapareja** [comment]
At the moment, both filters can be hidden with the prop:"control". I didn't see it in d2-components README, I can update it.
Do you want something like this?
![image](https://user-images.githubusercontent.com/24606534/69221184-f4d70480-0b76-11ea-824e-8e90ee4018ff.png)
