### ISSUE TITLE
User Roles extension

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/project-monitoring-app#40]
General:
- [x] Remove App roles
- [x] Feedback -> No change
- PM Reporting Analyst (Configurator) 
   - [x] Change name to 'Data Reviewer'
   - [ ] Change available actions: Go to Dashboard, Edit (only step 2 and 4), Add Target Values, Go to Data Entry, Generate/Configure MER, Download Data. IMPORTANT NOTE: He is not allowed to create a project. Only the admin can create a project
- PM Analyser
   - [x] Change name to 'Data Viewer'
   - [x] Change available actions: Go to Dashboard, Download Data
- PM Superuser
   - [x] Change name to 'PM Admin'
   - [ ] Custom indicators are only visible/selectable by the admin
- PM Encoder
   - [x] Change name to 'Data Entry'
   - [x] Change available actions: Go to Data Entry, Add Target Values, Go to Dashboard, Download Data
- [x] Add to all of them the authority to see the app except Feedback
- [x] All of them should be able to list all the project and show the details

**Comment by laurapareja** [comment]
There is a card ( #67 ) with the uncompleted tasks
