### ISSUE TITLE
Use new ObjecstTable for project list

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/project-monitoring-app#47]
Check PR by @SferaDev with D2ObjectsTable

https://github.com/EyeSeeTea/d2-ui-components/pull/92

Probably not, because we have JS array, manually filtered by attribute

**Comment by SferaDev** [comment]
Right now we have the following API available:

```ts
    const { loading, data, error, refetch } = useD2ApiData(apiMethod({
        order: `id:iasc`,
        pageSize: 10,
    }));

    useEffect(
        () =>
            refetch(
                apiMethod({
                    order: `${sorting.field}:i${sorting.order}`,
                    page: pagination.page,
                    pageSize: pagination.pageSize,
                    filter: {
                        name: { ilike: search },
                        ...apiQuery.filter,
                    },
                })
            ),
        [apiMethod, refetch, sorting, pagination, search]
    );
```

This snippet allows us to fetch an initial state and update it with UI filters on-demand without needing any kind of Model. However we do not have any option to post-process the results.

I would like, if possible, try to follow this ``fetch-data-in-ui`` pattern that react, apollo and DHIS2 are pushing ahead and leverage the use we have on models for simple ``fetch-and-print`` pages.

I would find useful however adding an optional argument to the hook that allows post-processing and transforming the response:

```ts
useD2ApiData(apiMethod({...}), Project.updateDataElementSelection);
```

Where ``updateDataElementSelection`` in the Project model takes the data from the response and returns the transformed objects. The default value for the transformer would be something as simple as ``objects => (objects)``.

NOTE: I'm using the project-monitoring-app as an example here but not 100% sure this code makes sense.
