### ISSUE TITLE
Selection of Indicators refinement

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/project-monitoring-app#57]
- [x] Update metadata to spreadsheet v3 -> local
- [x] Script: warning if dataElement code is already processed (detects DEs in multiple tabs)
- [x] Script: validate that paired are always: Benefit -> People 
- [x] Allow multiple paired data elements:
If we have n benefits -> 1 people 
![image](https://user-images.githubusercontent.com/6850223/74650632-0a5dc980-517a-11ea-896f-dc2b39da10ef.png)
Create n pairs of (people,benefit)
- [x] Test cases: https://github.com/EyeSeeTea/project-monitoring-app/wiki
- [x] Review if this case is working as expected:
At the highlighted indicators in the protection tab.  The indicators are paired with a sub indicator (even as a global indicator).  I’m a little uneasy about this from a consistency standpoint- but, if necessary, can the system also handle this?
- [x] Do not let the user unselect a global indicator if a sub in series is selected

- [x] Review corner case: For example: Agriculture -> _# of people trained on improved agriculture technologies/practices_, is a global data element but it's hidden because it's a paired element of others DEs. Additionally, it won't be selected when a sub of that series is selected.
- [x] Update metadata to spreadsheet v3 -> dev2

![image001](https://user-images.githubusercontent.com/6850223/74661957-e5c11c00-5190-11ea-8cd1-f73085f21c5c.png)

**Comment by adrianq** [comment]
Blessed issues:
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/32
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/32
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/35
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/36
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/37
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/38
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/40
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/41
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/58
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/68
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/69
