### ISSUE TITLE
Extend dashboard tables

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/project-monitoring-app#91]
See https://docs.google.com/document/d/1SlzPa0l0C8up0b69gFWT-1SfSNV4k8hD/edit
- [x] General Data View
   - [x] General Data View - Benefits
   - [x] General Data View - People
-> Split 'Target vs Actual' table and include disaggregations (new/recurring and male/female) for people

   - [x] General Data View - Unique People
-> Same as behaviour but including only new
-> Try to display all tables in the same row in the dashboard (read comment in the doc)

- [x] Percent achieved
   - [x] Percent achieved - Benefits
   - [x] Percent achieved - People
-> This cannot be done as the table is mixing DEs and Indicators as if they were the same object. We will use instead 'Target vs Actual achieved' but we will add the legend when the target is not achieved.

   - [x] Percent achieved - Percent achieved
-> Two new bar charts showing: all indicators disaggregated per month and all indicators for the whole project

- [x] Gender - Total Males versus Total Females
-> New bar chart showing the new people disaggregated by gender

- [x] Cost/Benefit - Benefits per person
-> We need a new indicator -> benefits / number of people. This needs to be added to the metadata. Only those DEs that are paired ( a benefit DE pointing to a people DE)
-> New bar chart showing this indicator

**Comment by adrianq** [comment]
General comments coming from #53

- [ ] Split table into two different tables: benefit - people
- [ ] Illustrate legend (background colours)
- Implement table for data approval (see #89)

**Comment by tokland** [comment]
Doubt(s):

- [ ] What criteria should we use to sort the indicators in the table/charts?
