### ISSUE TITLE
Implement MER section

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/project-monitoring-app#93]
- [x] Use landing page -> Reports
- [x] Month selector: use new DatePicker with year/month.
- [x] Org unit tree: maxLevel = 2, only 1 orgUnit with radio button
- [x] Get existing data from dataStore 
- [x] Target/actual table, use analytics (with comments, inline textField) for projects active in current month
- [x] 3 multiline info fields.
- [x] Staff table (inline textField)
- [x] \[Download\] -> xlsx
- [x] \[Save\] -> Save/update dataStore 
- [x] Load data from dataStore if report existed.
- [x] If any data was entered/modified then ask for confirmation on back (<- top-left button)
- [x] Textareas con margin and border
- [x] OrgUnitSelector with custom height (and set scrollbar to auto) -> https://github.com/EyeSeeTea/d2-ui-components/pull/102
- [x] OrgUnitSelector: get name on select (request api)
- [x] Add a new textfield 'Country Director', store in the system and use in the excel header
- [x] Excel: styles
- [x] Excel: save MER-ORGUNIT-YYYY_MM.xslx
- [x] Excel: Data table should go to the second tab as is. Second tab should be named 'Activities'
- [x] Tests (unit)

Excel with Report -> https://docs.google.com/spreadsheets/d/15aDry31k1rgbElcZB729zAHubbxoyHCM/edit#gid=1614909697
Doc with workflow -> https://docs.google.com/document/d/1SUqADcbDkW5WIHYi85IiIuzu0Ru2P-pH/edit
Mock up -> https://docs.google.com/drawings/d/1D3dreCGanjITqbFoYX0He9hQQh2snpFwOY0Sz5dKFpk/edit

![MER mockup](https://user-images.githubusercontent.com/6850223/70718451-25c6d700-1ce8-11ea-8d5a-15bf03022e6b.png)

Changes to the mockup
- Include the Staff Summary table
- Date picker should allow only monthly selection

**Comment by tokland** [comment]
```
interface DataStoreMER2 {
    "mer-ORGUNITLEVEL2ID-201912": {
        created: string;
        createdBy: string;
        updated: string;
        updatedBy: string;
        executiveSummary: string;
        ministrySummary: string;
        projectActivitiesNextMonth: string;
        staffSumary: {
            nationalStaff: {
                fullTime: number;
                partTime: number;
            };
            // 6 in total: nationalStaff, IFS, IFS Dependents, Regional Staff,
            // Regional Staff Dependents, Interns
        };
        comments: {
            [orgUnitLevel3Id: string]: {
                [dataElementId: string]: string;
            };
        };
    };
}
```

**Comment by adrianq** [comment]
@tokland Great job! It is working as expected and we will have to time iterate over this version. A few comments, most of them can be tackled at a later stage (will create cards):
- Textfield lines for textareas are going beyond the right border
![image](https://user-images.githubusercontent.com/6850223/71367160-2a1eaa00-259c-11ea-9c35-d5afd8b2fdb7.png)
- On focus, line should probably change to blue as in DHIS2 [Issue](https://github.com/EyeSeeTea/project-monitoring-app/issues/105)
- JSON file is generated from what we currently have on the screen instead of what is actually saved. I have the impression you are checking when the user tried to go out the page if there is any unsaved change and if so displays a warning message. What about displaying something like 'You are trying to download an unsaved report. Do you want to save before downloading?'
- Google suggestion in the textfield. I think this is something we solved in the vaccination project. If you can please recover that code... The client will say something about this sooner rather than later.
![image](https://user-images.githubusercontent.com/6850223/71368364-a961ad00-259f-11ea-86f5-8a61230be997.png)
- Problem with a dataelement that causes MER report to fail. Data Element Uid: K6mAC5SiO29 Not sure what happened but I have to manually delete this data element from the list of select indicator in the data store
- Question: can certain fields like 'Achieved' or the totals in the table be calculated as a formula in the excel file? Does the library support it? I have the impression they may want this way.

I am merging this code anyway as none of these points is critical but let's talk about them once you are back from hols

**Comment by tokland** [comment]
> * JSON file is generated from what we currently have on the screen instead of what is actually saved. I have the impression you are checking when the user tried to go out the page if there is any unsaved change and if so displays a warning message. What about displaying something like 'You are trying to download an unsaved report. Do you want to save before downloading?'

Yes, now it works like a document in a text editor, download and save are independent actions. Another solution would be disabling `[Download]` unless file is saved. And disable button `[Save]` if project already saved. Let's talk on the next meeting.

> * Google suggestion in the textfield. I think this is something we solved in the vaccination project. 

There we had custom forms, here we cannot change the automatic HTML form. In other projects, we used CustomCssJs. It's a bit surprising nobody reported it in data-entry. 

> * Problem with a dataelement that causes MER report to fail. Data Element Uid: K6mAC5SiO29

I found the bug, it was a paired data element, in config we have the main ones.  Fixed, will upload in next PR.

> * Question: can certain fields like 'Achieved' or the totals in the table be calculated as a formula in the excel file? Does the library support it? I have the impression they may want this way.

Sure, exceljs supports formulas.

**Comment by adrianq** [comment]
https://github.com/EyeSeeTea/project-monitoring-app/issues/106

> * JSON file is generated from what we currently have on the screen instead of what is actually saved. I have the impression you are checking when the user tried to go out the page if there is any unsaved change and if so displays a warning message. What about displaying something like 'You are trying to download an unsaved report. Do you want to save before downloading?'

> Yes, now it works like a document in a text editor, download and save are independent actions. Another solution would be disabling `[Download]` unless file is saved. And disable button `[Save]` if project already saved. Let's talk on the next meeting.

Sure, just created an issue to take care of this: https://github.com/EyeSeeTea/project-monitoring-app/issues/107

> * Google suggestion in the textfield. I think this is something we solved in the vaccination project. 

> There we had custom forms, here we cannot change the automatic HTML form. In other projects, we used CustomCssJs. It's a bit surprising nobody reported it in data-entry. 

Strange, did you search in JIRA? Maybe we can create an issue in the DHIS2 JIRA...

> * Problem with a dataelement that causes MER report to fail. Data Element Uid: K6mAC5SiO29

> I found the bug, it was a paired data element, in config we have the main ones.  Fixed, will upload in next PR.

Did you fix it in this [PR](https://github.com/EyeSeeTea/project-monitoring-app/pull/103)? or in the next PR after hols?

> * Question: can certain fields like 'Achieved' or the totals in the table be calculated as a formula in the excel file? Does the library support it? I have the impression they may want this way.

> Sure, exceljs supports formulas.

Issue to take care of this in the future: https://github.com/EyeSeeTea/project-monitoring-app/issues/106
